GET localhost:8080/ping

###
GET localhost:8080/orders

###
POST localhost:8080/add
Content-Type: application/json

[
  {
    "id": 0,
    "name": "test1",
    "cost": 75
  }
]

###
GET localhost:8080/order/1