spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baza
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file:
    name: homework31.log

server:
  port: 8080